#!/bin/sh
# elvis: homemanageroptions -- Search Home Manager Options
# Author: artsbymat

. surfraw || exit 1

w3_config_hook() {
	def SURFRAW_home_manager_release "master" # Default release: master
}

w3_usage_hook() {
	cat <<EOF
Usage: $w3_argv0 [options] [search-string]
Description:
  Search for options in Home Manager Options (https://home-manager-options.extranix.com/)

Local options:
 -release=RELEASE_TYPE        Release type for search results
 -r=RELEASE_TYPE
           master             | Search in master release (default)
           stable             | Search in stable release
                                Environment: SURFRAW_home_manager_release
                                Default: master
EOF
	w3_global_usage
}

w3_parse_option_hook() {
	opt="$1"
	optarg="$2"
	case "$opt" in
	-release=*) setopt SURFRAW_home_manager_release "$optarg" ;;
	-r=*) setopt SURFRAW_home_manager_release "$optarg" ;;
	*) return 1 ;;
	esac
	return 0
}

w3_config
w3_parse_args "$@"
# w3_args now contains list of arguments

# Construct the URL
base_url="https://home-manager-options.extranix.com/"
release_type="$SURFRAW_home_manager_release"

if [ -z "$w3_args" ]; then
	w3_browse_url "${base_url}"
else
	escaped_args=$(w3_url_of_arg "$w3_args")
	w3_browse_url "${base_url}?query=${escaped_args}&release=${release_type}"
fi
