#!/bin/sh
# elvis: myanimelist -- Search anime/manga on MyAnimeList
# Author: Your Name

. surfraw || exit 1

w3_config_hook() {
    def SURFRAW_mal_category "all"
}

w3_usage_hook() {
    cat <<EOF
Usage: $w3_argv0 [options] [search-string]
Description:
  Search anime/manga on MyAnimeList (https://myanimelist.net)

Local options
 -category=CATEGORY      Search category (default: all)
 -cat=CATEGORY
           all           |       All categories (default)
           anime         |       Anime only
           manga         |       Manga only
           etc...        |       Other MyAnimeList categories
                                Environment: SURFRAW_mal_category
                                Default: all
EOF
    w3_global_usage
}

w3_parse_option_hook() {
    opt="$1"
    optarg="$2"
    case "$opt" in
    -category=*) setopt SURFRAW_mal_category "$optarg" ;;
    -cat=*) setopt SURFRAW_mal_category "$optarg" ;;
    *) return 1 ;;
    esac
    return 0
}

w3_config
w3_parse_args "$@"

base_url="https://myanimelist.net/search/all"
category="$SURFRAW_mal_category"

if [ -z "$w3_args" ]; then
    w3_browse_url "${base_url}?cat=${category}"
else
    escaped_args=$(w3_url_of_arg "$w3_args")
    w3_browse_url "${base_url}?q=${escaped_args}&cat=${category}"
fi
